name: Episode 13 - Language server checks

on: push

jobs:
  check_lsp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: episode-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: poetry install --no-root --with dev
      - name: Cache venv created by poetry (configured to be in '.venv')
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Run pyright
        run: |
          poetry run pyright
